version: '3'

volumes:
  postgres_data:

services:
  django: &django
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    image: lem_local_django
    container_name: lem_local_django
    # platform: linux/x86_64
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/src:z
    env_file:
      - ./.envs/local/django.env
      - ./.envs/local/postgres.env
    ports:
      - "8000:8000"
    command: /start-django.sh

  postgres:
    image: postgres:15-alpine
    container_name: lem_local_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.envs/local/postgres.env

  redis:
    image: redis:7
    container_name: lem_local_redis

  celeryworker:
    <<: *django
    image: lem_local_celeryworker
    container_name: lem_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker.sh

  celerybeat:
    <<: *django
    image: lem_local_celerybeat
    container_name: lem_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat.sh

  flower:
    <<: *django
    image: lem_local_flower
    container_name: lem_local_flower
    ports:
      - "5555:5555"
    command: /start-flower.sh
