# Generated by Django 4.1.4 on 2023-01-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generic", "0002_reaction_delete_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="object_id",
            field=models.PositiveBigIntegerField(),
        ),
    ]
