# Generated by Django 4.1.4 on 2023-01-26 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_author_alter_book_genre_book_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="ISBN_id",
        ),
        migrations.RemoveField(
            model_name="book",
            name="catalog_number",
        ),
        migrations.RemoveField(
            model_name="book",
            name="dimensions",
        ),
        migrations.RemoveField(
            model_name="book",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="book",
            name="language_provided",
        ),
        migrations.RemoveField(
            model_name="book",
            name="original_language",
        ),
        migrations.RemoveField(
            model_name="book",
            name="publisher",
        ),
        migrations.AlterField(
            model_name="book",
            name="original_title",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_title",
                        message="Title must be Alphanumeric",
                        regex="^[a-zA-Z0-9]*$",
                    )
                ],
            ),
        ),
    ]
