# Generated by Django 4.1.4 on 2023-01-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_remove_book_isbn_id_remove_book_catalog_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.ManyToManyField(related_name="books", to="books.genre"),
        ),
    ]
