# Generated by Django 4.1.4 on 2023-01-27 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_book_isbn_id_book_catalog_number_book_dimensions_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="author",
            new_name="authors",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="genre",
            new_name="genres",
        ),
    ]
