# Generated by Django 4.1.4 on 2023-01-07 21:35

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="file",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="highlight",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="like",
            options={"ordering": ("-created_at",)},
        ),
        migrations.RemoveField(
            model_name="comment",
            name="created",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="edited",
        ),
        migrations.RemoveField(
            model_name="file",
            name="created",
        ),
        migrations.RemoveField(
            model_name="file",
            name="edited",
        ),
        migrations.RemoveField(
            model_name="highlight",
            name="created",
        ),
        migrations.RemoveField(
            model_name="highlight",
            name="edited",
        ),
        migrations.RemoveField(
            model_name="image",
            name="created",
        ),
        migrations.RemoveField(
            model_name="image",
            name="edited",
        ),
        migrations.RemoveField(
            model_name="like",
            name="created",
        ),
        migrations.RemoveField(
            model_name="like",
            name="edited",
        ),
        migrations.RemoveField(
            model_name="news",
            name="created",
        ),
        migrations.RemoveField(
            model_name="news",
            name="edited",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="created",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="edited",
        ),
        migrations.AddField(
            model_name="comment",
            name="created_at",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="modified_at",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="file",
            name="created_at",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="file",
            name="modified_at",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="highlight",
            name="created_at",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="highlight",
            name="modified_at",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="image",
            name="created_at",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="modified_at",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="like",
            name="created_at",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="like",
            name="modified_at",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="news",
            name="created_at",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="news",
            name="modified_at",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="created_at",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tag",
            name="modified_at",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="name"
            ),
        ),
    ]
