# Generated by Django 4.1.4 on 2023-01-08 10:33

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_comment_options_alter_file_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="title"
            ),
        ),
    ]
