# Generated by Django 4.1.4 on 2023-01-27 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_tag_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="highlight",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="highlight",
            name="user",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="user",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Highlight",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
