# Generated by Django 4.1.4 on 2023-01-27 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_remove_highlight_content_type_remove_highlight_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="body",
            new_name="content",
        ),
    ]
